// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

[Table("EXCEPTION_LOG")]
public partial class EXCEPTION_LOG
{
    [Key]
    public int ID { get; set; }

    public string MESSAGE { get; set; }

    public string MESSAGE_TEMPLATE { get; set; }

    [StringLength(128)]
    public string LEVEL { get; set; }

    public DateTimeOffset TIME_STAMP { get; set; }

    public string EXCEPTION { get; set; }

    public string PROPERTY { get; set; }

    [Required]
    public string LOG_EVENT { get; set; }
}