// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

public partial class ICContext : DbContext
{
    public ICContext(DbContextOptions<ICContext> options)
        : base(options)
    {
    }

    public virtual DbSet<EXCEPTION_LOG> EXCEPTION_LOGs { get; set; }

    public virtual DbSet<ORDER> ORDERs { get; set; }

    public virtual DbSet<ORDER_LOG> ORDER_LOGs { get; set; }

    public virtual DbSet<PARAMETER> PARAMETERs { get; set; }

    public virtual DbSet<REPORT> REPORTs { get; set; }

    public virtual DbSet<SYMBOL> SYMBOLs { get; set; }

    public virtual DbSet<TRADING_VIEW_ANALYSIS> TRADING_VIEW_ANALYSES { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.UseCollation("SQL_Latin1_General_CP1_CI_AI");

        modelBuilder.Entity<EXCEPTION_LOG>(entity =>
        {
            entity.Property(e => e.EXCEPTION).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.LEVEL).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.LOG_EVENT).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.MESSAGE).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.MESSAGE_TEMPLATE).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.PROPERTY).UseCollation("Turkish_CI_AS");
        });

        modelBuilder.Entity<ORDER>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__ORDER__3214EC27707FBF41");

            entity.Property(e => e.BINANCE_CLOSE_ORDER_ID).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.BINANCE_ORDER_ID).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.BINANCE_SL_ORDER_ID).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.BINANCE_STATUS).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.BINANCE_TP_ORDER_ID).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.BINANCE_TRAILING_ORDER_ID).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.CLOSE_PRICE_UPDATED).HasDefaultValue(false);
            entity.Property(e => e.CLOSE_TYPE).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.INTERVAL_TYPE).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.ORDER_SIDE).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.ORDER_TYPE).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.SIGNAL_TYPE).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.STATUS).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.STOP_PRICE_UPDATED).HasDefaultValue(false);
            entity.Property(e => e.SYMBOL).UseCollation("Turkish_CI_AS");
        });

        modelBuilder.Entity<ORDER_LOG>(entity =>
        {
            entity.Property(e => e.LOG_TYPE).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.REQ_BODY).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.REQ_PATH).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.RES_BODY).UseCollation("Turkish_CI_AS");
        });

        modelBuilder.Entity<PARAMETER>(entity =>
        {
            entity.Property(e => e.CODE).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.DESCR).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.VALUE).UseCollation("Turkish_CI_AS");
        });

        modelBuilder.Entity<REPORT>(entity =>
        {
            entity.Property(e => e.REPORT_DATE).HasDefaultValueSql("(getdate())");
        });

        modelBuilder.Entity<SYMBOL>(entity =>
        {
            entity.Property(e => e.CODE).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.DESCR).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.MIN_AMOUNT).UseCollation("SQL_Latin1_General_CP1_CI_AS");
            entity.Property(e => e.PRICE_STEP).UseCollation("SQL_Latin1_General_CP1_CI_AS");
        });

        modelBuilder.Entity<TRADING_VIEW_ANALYSIS>(entity =>
        {
            entity.HasKey(e => e.ID).HasName("PK__TradingV__3214EC07FD4E1A32");

            entity.Property(e => e.INDICATOR_JSON).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.INSERT_DATE_TIME).HasDefaultValueSql("(getdate())");
            entity.Property(e => e.INTERVAL).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.OSCILLATOR_JSON).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.SUMMARY_JSON).UseCollation("Turkish_CI_AS");
            entity.Property(e => e.SYMBOL_CODE).UseCollation("Turkish_CI_AS");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}