// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Data.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Data.Models
{
    public partial interface IICContextProcedures
    {
        Task<List<spGetCoinsResult>> spGetCoinsAsync(string pDateTime, int? pMin, double? pPercentage, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spReportResult>> spReportAsync(string pInterval, int? pCnt, string pRecommendation, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<spRunReportResult>> spRunReportAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
