// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

[Table("ORDER_LOG")]
public partial class ORDER_LOG
{
    [Key]
    public int ID { get; set; }

    public int? ORDER_ID { get; set; }

    [Unicode(false)]
    public string REQ_PATH { get; set; }

    [Unicode(false)]
    public string REQ_BODY { get; set; }

    [Unicode(false)]
    public string RES_BODY { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string LOG_TYPE { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? INSERT_DATE_TIME { get; set; }
}