// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

[Table("ORDER")]
public partial class ORDER
{
    [Key]
    public int ID { get; set; }

    [StringLength(10)]
    public string STATUS { get; set; }

    [StringLength(50)]
    public string SYMBOL { get; set; }

    [StringLength(4)]
    public string ORDER_SIDE { get; set; }

    [StringLength(50)]
    public string ORDER_TYPE { get; set; }

    [StringLength(5)]
    [Unicode(false)]
    public string INTERVAL_TYPE { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal QUANTITY { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? OPEN_PRICE { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? CLOSE_PRICE { get; set; }

    public bool? CLOSE_PRICE_UPDATED { get; set; }

    [StringLength(50)]
    public string CLOSE_TYPE { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? OPENED_PRICE { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? STOP_PRICE { get; set; }

    public bool? STOP_PRICE_UPDATED { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal? CALL_BACK_RATE { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? EXECUTED_QUANTITY { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? CLOSED_PRICE { get; set; }

    [StringLength(50)]
    public string SIGNAL_TYPE { get; set; }

    [Column(TypeName = "decimal(18, 4)")]
    public decimal? INDICATOR_VALUE { get; set; }

    [StringLength(50)]
    public string BINANCE_ORDER_ID { get; set; }

    [StringLength(50)]
    public string BINANCE_CLOSE_ORDER_ID { get; set; }

    [StringLength(50)]
    public string BINANCE_TRAILING_ORDER_ID { get; set; }

    [StringLength(50)]
    public string BINANCE_TP_ORDER_ID { get; set; }

    [StringLength(50)]
    public string BINANCE_SL_ORDER_ID { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string BINANCE_STATUS { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? INSERT_DATETIME { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? UPDATE_DATETIME { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? CLOSED_DATETIME { get; set; }

    [Unicode(false)]
    public string ORDER_RESULT_JSON { get; set; }
}