// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

[Table("PARAMETER")]
public partial class PARAMETER
{
    [Key]
    [StringLength(50)]
    [Unicode(false)]
    public string CODE { get; set; }

    [StringLength(50)]
    [Unicode(false)]
    public string VALUE { get; set; }

    [StringLength(500)]
    [Unicode(false)]
    public string DESCR { get; set; }
}