// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

[Keyless]
[Table("REPORT")]
public partial class REPORT
{
    [Column(TypeName = "datetime")]
    public DateTime REPORT_DATE { get; set; }

    [Required]
    [StringLength(20)]
    public string SYMBOL_CODE { get; set; }

    public int CNT { get; set; }

    [Required]
    [StringLength(20)]
    public string RECOMMENDATION { get; set; }
}