// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

[Table("SYMBOL")]
public partial class SYMBOL
{
    [Key]
    public int ID { get; set; }

    [Required]
    [StringLength(20)]
    public string CODE { get; set; }

    [StringLength(10)]
    public string MIN_AMOUNT { get; set; }

    public int? ACTIVE { get; set; }

    [StringLength(10)]
    public string PRICE_STEP { get; set; }

    [Column("5m", TypeName = "smalldatetime")]
    public DateTime? _5m { get; set; }

    [Column("15m", TypeName = "smalldatetime")]
    public DateTime? _15m { get; set; }

    [Column("30m", TypeName = "smalldatetime")]
    public DateTime? _30m { get; set; }

    [Column("1h", TypeName = "smalldatetime")]
    public DateTime? _1h { get; set; }

    [Column("4h", TypeName = "smalldatetime")]
    public DateTime? _4h { get; set; }

    [Column("1d", TypeName = "smalldatetime")]
    public DateTime? _1d { get; set; }

    [Column("1m", TypeName = "smalldatetime")]
    public DateTime? _1m { get; set; }

    public short ON_OFF { get; set; }

    public short RSI { get; set; }

    public short WR { get; set; }

    public short BB { get; set; }

    public int? BIST_X { get; set; }

    public string DESCR { get; set; }
}