// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Data.Models;

[Table("TRADING_VIEW_ANALYSIS")]
public partial class TRADING_VIEW_ANALYSIS
{
    [Key]
    public int ID { get; set; }

    [StringLength(50)]
    public string INTERVAL { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime INSERT_DATE_TIME { get; set; }

    [Required]
    [StringLength(20)]
    public string SYMBOL_CODE { get; set; }

    [Column(TypeName = "decimal(18, 8)")]
    public decimal CLOSE_VALUE { get; set; }

    [Required]
    public string INDICATOR_JSON { get; set; }

    [Required]
    public string OSCILLATOR_JSON { get; set; }

    [Required]
    public string SUMMARY_JSON { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime ANALYSIS_TIME { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CREATED_AT { get; set; }
}